DROP TABLE CompagnieVol CASCADE;
DROP TABLE CompagnieFabriquant CASCADE;
DROP TABLE Modele CASCADE;

DROP TABLE Modele_Porte_Embarquement CASCADE;
DROP TABLE Avion CASCADE;
DROP TABLE Passager CASCADE;

DROP TABLE PersonnelTechnique CASCADE;
DROP TABLE Steward CASCADE;
DROP TABLE Pilote CASCADE;

DROP TABLE HoteDAccueil CASCADE;
DROP TABLE Terminal CASCADE;
DROP TABLE PorteEmbarquement CASCADE;


DROP TABLE Vol CASCADE;
DROP TABLE Bagage CASCADE;
DROP TABLE Vol_Steward CASCADE;

DROP TABLE VolDepart CASCADE;
DROP TABLE VolArrive CASCADE;
DROP TABLE Personne CASCADE;


